name: Spawnr
main: com.cydoniarp.amd3th.spawnr.Spawnr
version: 1.6
author: amd3th
description: Sets player initial spawn and respawn location to exact coordinates that OP sets as well as player homes.
commands:
  spawnr:
    description: Sets spawn location coords.
    usage: Incorrect usage try /spawnr set | tp | sethome | home